export const resources = {
  documentation: [
    {
      title: "MDN Web Docs",
      description: "The most comprehensive and authoritative web development documentation",
      url: "https://developer.mozilla.org",
      category: "Reference",
      image: "/placeholder.svg?height=120&width=200&text=MDN",
      color: "from-blue-500 to-blue-600",
      icon: "📚",
    },
    {
      title: "React Documentation",
      description: "Official React docs with interactive examples and best practices",
      url: "https://react.dev",
      category: "Framework",
      image: "/placeholder.svg?height=120&width=200&text=React",
      color: "from-cyan-500 to-blue-500",
      icon: "⚛️",
    },
    {
      title: "CSS-Tricks",
      description: "Daily articles about CSS, HTML, JavaScript, and web design",
      url: "https://css-tricks.com",
      category: "CSS",
      image: "/placeholder.svg?height=120&width=200&text=CSS-Tricks",
      color: "from-green-500 to-teal-500",
      icon: "🎨",
    },
    {
      title: "TypeScript Handbook",
      description: "Complete guide to TypeScript with examples and advanced concepts",
      url: "https://www.typescriptlang.org/docs/",
      category: "Language",
      image: "/placeholder.svg?height=120&width=200&text=TypeScript",
      color: "from-blue-600 to-indigo-600",
      icon: "📘",
    },
    {
      title: "Next.js Documentation",
      description: "Production-ready React framework with server-side rendering",
      url: "https://nextjs.org/docs",
      category: "Framework",
      image: "/placeholder.svg?height=120&width=200&text=Next.js",
      color: "from-gray-800 to-gray-900",
      icon: "▲",
    },
    {
      title: "Tailwind CSS Docs",
      description: "Utility-first CSS framework documentation and component examples",
      url: "https://tailwindcss.com/docs",
      category: "CSS",
      image: "/placeholder.svg?height=120&width=200&text=Tailwind",
      color: "from-teal-400 to-blue-500",
      icon: "🌊",
    },
  ],
}