export const resources = {
  tools: [
    {
      title: "VS Code",
      description: "Free, powerful source-code editor with excellent frontend support",
      url: "https://code.visualstudio.com",
      category: "Editor",
      image: "/placeholder.svg?height=120&width=200&text=VS+Code",
      color: "from-blue-600 to-blue-700",
      icon: "💻",
    },
    {
      title: "Figma",
      description: "Collaborative interface design tool for teams",
      url: "https://figma.com",
      category: "Design",
      image: "/placeholder.svg?height=120&width=200&text=Figma",
      color: "from-purple-500 to-pink-500",
      icon: "🎨",
    },
    {
      title: "Chrome DevTools",
      description: "Built-in browser developer tools for debugging and optimization",
      url: "https://developer.chrome.com/docs/devtools",
      category: "Debug",
      image: "/placeholder.svg?height=120&width=200&text=DevTools",
      color: "from-red-500 to-orange-500",
      icon: "🔧",
    },
    {
      title: "GitHub",
      description: "Version control and collaboration platform for developers",
      url: "https://github.com",
      category: "Version Control",
      image: "/placeholder.svg?height=120&width=200&text=GitHub",
      color: "from-gray-800 to-gray-900",
      icon: "🐙",
    },
    {
      title: "Netlify",
      description: "Deploy and host your frontend projects with ease",
      url: "https://netlify.com",
      category: "Hosting",
      image: "/placeholder.svg?height=120&width=200&text=Netlify",
      color: "from-teal-500 to-cyan-600",
      icon: "🚀",
    },
    {
      title: "Vercel",
      description: "Platform for frontend frameworks and static sites",
      url: "https://vercel.com",
      category: "Hosting",
      image: "/placeholder.svg?height=120&width=200&text=Vercel",
      color: "from-black to-gray-800",
      icon: "▲",
    },
  ],
}
