export const resources = {
  videos: [
   {
      title: "freeCodeCamp",
      description: "Free coding tutorials, courses, and certification programs",
      url: "https://youtube.com/freecodecamp",
      category: "General",
      thumbnail: "/placeholder.svg?height=120&width=200&text=freeCodeCamp",
      color: "from-green-600 to-green-700",
      duration: "Various",
    },
    {
      title: "Traversy Media",
      description: "Web development tutorials, crash courses, and project builds",
      url: "https://youtube.com/traversymedia",
      category: "General",
      thumbnail: "/placeholder.svg?height=120&width=200&text=Traversy+Media",
      color: "from-red-500 to-red-600",
      duration: "15-60 min",
    },
    {
      title: "The Net Ninja",
      description: "Frontend development tutorials and modern web technologies",
      url: "https://youtube.com/thenetninja",
      category: "Frontend",
      thumbnail: "/placeholder.svg?height=120&width=200&text=Net+Ninja",
      color: "from-orange-500 to-red-500",
      duration: "10-30 min",
    },
    {
      title: "Kevin Powell",
      description: "CSS tutorials and tips to make you fall in love with CSS",
      url: "https://youtube.com/kevinpowell",
      category: "CSS",
      thumbnail: "/placeholder.svg?height=120&width=200&text=Kevin+Powell",
      color: "from-blue-500 to-purple-600",
      duration: "5-20 min",
    },
    {
      title: "Web Dev Simplified",
      description: "Simplified web development tutorials for all skill levels",
      url: "https://youtube.com/webdevsimplified",
      category: "General",
      thumbnail: "/placeholder.svg?height=120&width=200&text=Web+Dev+Simplified",
      color: "from-indigo-500 to-blue-600",
      duration: "10-25 min",
    },
    {
      title: "Fireship",
      description: "High-intensity code tutorials and tech news in 100 seconds",
      url: "https://youtube.com/fireship",
      category: "General",
      thumbnail: "/placeholder.svg?height=120&width=200&text=Fireship",
      color: "from-orange-400 to-red-500",
      duration: "1-10 min",
    },
  ],
}