import type { LearningPath } from '../../types/roadmap';

export const learningPaths: LearningPath[] = [
		{
			id: 'beginner',
			title: 'Beginner Path',
			description: 'Perfect for complete beginners. Learn HTML, CSS, and basic JavaScript through fun, hands-on projects.',
			difficulty: 'beginner',
			duration: '4-6 weeks',
			completedChallenges: 0,
			progressPercentage: 0,
			technologies: ['HTML', 'CSS', 'JavaScript'],
			estimatedWeeks: 6,
			milestones: [],
		},
		{
			id: 'intermediate',
			title: 'Intermediate Path',
			description: 'Ready for React and modern development? Build dynamic applications with APIs and state management.',
			difficulty: 'intermediate',
			duration: '6-8 weeks',
			completedChallenges: 0,
			progressPercentage: 0,
			technologies: ['React', 'APIs', 'State Management', 'Testing'],
			estimatedWeeks: 8,
			milestones: [],
		},
		{
			id: 'advanced',
			title: 'Advanced Path',
			description: 'Enterprise-level challenges with TypeScript, testing, and advanced patterns for production-ready code.',
			difficulty: 'advanced',
			duration: '8-10 weeks',
			completedChallenges: 0,
			progressPercentage: 0,
			technologies: ['TypeScript', 'Performance', 'Architecture', 'Deployment'],
			estimatedWeeks: 10,
			milestones: [],
		},
];
