export const challenges = [
  {
    id: 1,
    title: 'Responsive Navigation Bar',
    difficulty: 'Beginner',
    tags: ['responsive', 'navigation', 'flexbox'],
    description:
      'Create a mobile-friendly navigation component with dropdown menus',
    image: '/placeholder.svg?height=200&width=300',
    estimatedTime: '30 min',
    submissions: 1250,
  },
  {
    id: 2,
    title: 'Todo App with Local Storage',
    difficulty: 'Intermediate',
    tags: ['dom', 'localStorage', 'events'],
    description: 'Build a fully functional todo application with persistence',
    image: '/placeholder.svg?height=200&width=300',
    estimatedTime: '2 hours',
    submissions: 890,
  },
  {
    id: 3,
    title: 'React Component Library',
    difficulty: 'Advanced',
    tags: ['components', 'props', 'typescript'],
    description: 'Design and implement reusable React components',
    image: '/placeholder.svg?height=200&width=300',
    estimatedTime: '4 hours',
    submissions: 456,
  },
  {
    id: 4,
    title: 'E-commerce Product Card',
    difficulty: 'Beginner',
    tags: ['HTML', 'CSS', 'Responsive'],
    description:
      'Create a modern product card with hover effects and responsive design',
    image: '/placeholder.svg?height=200&width=300',
    estimatedTime: '2-3 hours',
    submissions: 1234,
  },
  {
    id: 5,
    title: 'Interactive Dashboard',
    difficulty: 'Intermediate',
    tags: ['React', 'JavaScript', 'Charts'],
    description: 'Build a data visualization dashboard with interactive charts',
    image: '/placeholder.svg?height=200&width=300',
    estimatedTime: '4-6 hours',
    submissions: 567,
  },
  {
    id: 6,
    title: 'Social Media Feed',
    difficulty: 'Advanced',
    tags: ['React', 'TypeScript', 'API'],
    description: 'Create a dynamic social media feed with infinite scroll',
    image: '/placeholder.svg?height=200&width=300',
    estimatedTime: '6-8 hours',
    submissions: 234,
  },
]
