/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as RoadmapIntermediateRouteImport } from './routes/roadmap/intermediate'
import { Route as RoadmapBeginnerRouteImport } from './routes/roadmap/beginner'
import { Route as RoadmapAdvancedRouteImport } from './routes/roadmap/advanced'
import { Route as ResourcesVideosRouteImport } from './routes/resources/videos'
import { Route as ResourcesToolsRouteImport } from './routes/resources/tools'
import { Route as ResourcesDocumentationRouteImport } from './routes/resources/documentation'
import { Route as FeedbackSubmissionIdRouteImport } from './routes/feedback/$submissionId'
import { Route as ChallengesIdIndexRouteImport } from './routes/challenges/$id/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIntermediateRoute = RoadmapIntermediateRouteImport.update({
  id: '/roadmap/intermediate',
  path: '/roadmap/intermediate',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapBeginnerRoute = RoadmapBeginnerRouteImport.update({
  id: '/roadmap/beginner',
  path: '/roadmap/beginner',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapAdvancedRoute = RoadmapAdvancedRouteImport.update({
  id: '/roadmap/advanced',
  path: '/roadmap/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesVideosRoute = ResourcesVideosRouteImport.update({
  id: '/resources/videos',
  path: '/resources/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesToolsRoute = ResourcesToolsRouteImport.update({
  id: '/resources/tools',
  path: '/resources/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDocumentationRoute = ResourcesDocumentationRouteImport.update({
  id: '/resources/documentation',
  path: '/resources/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSubmissionIdRoute = FeedbackSubmissionIdRouteImport.update({
  id: '/feedback/$submissionId',
  path: '/feedback/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdIndexRoute = ChallengesIdIndexRouteImport.update({
  id: '/challenges/$id/',
  path: '/challenges/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/feedback/$submissionId': typeof FeedbackSubmissionIdRoute
  '/resources/documentation': typeof ResourcesDocumentationRoute
  '/resources/tools': typeof ResourcesToolsRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/roadmap/advanced': typeof RoadmapAdvancedRoute
  '/roadmap/beginner': typeof RoadmapBeginnerRoute
  '/roadmap/intermediate': typeof RoadmapIntermediateRoute
  '/challenges': typeof ChallengesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/challenges/$id': typeof ChallengesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/feedback/$submissionId': typeof FeedbackSubmissionIdRoute
  '/resources/documentation': typeof ResourcesDocumentationRoute
  '/resources/tools': typeof ResourcesToolsRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/roadmap/advanced': typeof RoadmapAdvancedRoute
  '/roadmap/beginner': typeof RoadmapBeginnerRoute
  '/roadmap/intermediate': typeof RoadmapIntermediateRoute
  '/challenges': typeof ChallengesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/challenges/$id': typeof ChallengesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/feedback/$submissionId': typeof FeedbackSubmissionIdRoute
  '/resources/documentation': typeof ResourcesDocumentationRoute
  '/resources/tools': typeof ResourcesToolsRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/roadmap/advanced': typeof RoadmapAdvancedRoute
  '/roadmap/beginner': typeof RoadmapBeginnerRoute
  '/roadmap/intermediate': typeof RoadmapIntermediateRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/challenges/$id/': typeof ChallengesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/feedback/$submissionId'
    | '/resources/documentation'
    | '/resources/tools'
    | '/resources/videos'
    | '/roadmap/advanced'
    | '/roadmap/beginner'
    | '/roadmap/intermediate'
    | '/challenges'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/challenges/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/feedback/$submissionId'
    | '/resources/documentation'
    | '/resources/tools'
    | '/resources/videos'
    | '/roadmap/advanced'
    | '/roadmap/beginner'
    | '/roadmap/intermediate'
    | '/challenges'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/challenges/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/login'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/feedback/$submissionId'
    | '/resources/documentation'
    | '/resources/tools'
    | '/resources/videos'
    | '/roadmap/advanced'
    | '/roadmap/beginner'
    | '/roadmap/intermediate'
    | '/challenges/'
    | '/resources/'
    | '/roadmap/'
    | '/settings/'
    | '/challenges/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SignupRoute: typeof SignupRoute
  FeedbackSubmissionIdRoute: typeof FeedbackSubmissionIdRoute
  ResourcesDocumentationRoute: typeof ResourcesDocumentationRoute
  ResourcesToolsRoute: typeof ResourcesToolsRoute
  ResourcesVideosRoute: typeof ResourcesVideosRoute
  RoadmapAdvancedRoute: typeof RoadmapAdvancedRoute
  RoadmapBeginnerRoute: typeof RoadmapBeginnerRoute
  RoadmapIntermediateRoute: typeof RoadmapIntermediateRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ChallengesIdIndexRoute: typeof ChallengesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/intermediate': {
      id: '/roadmap/intermediate'
      path: '/roadmap/intermediate'
      fullPath: '/roadmap/intermediate'
      preLoaderRoute: typeof RoadmapIntermediateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/beginner': {
      id: '/roadmap/beginner'
      path: '/roadmap/beginner'
      fullPath: '/roadmap/beginner'
      preLoaderRoute: typeof RoadmapBeginnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/advanced': {
      id: '/roadmap/advanced'
      path: '/roadmap/advanced'
      fullPath: '/roadmap/advanced'
      preLoaderRoute: typeof RoadmapAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/videos': {
      id: '/resources/videos'
      path: '/resources/videos'
      fullPath: '/resources/videos'
      preLoaderRoute: typeof ResourcesVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/tools': {
      id: '/resources/tools'
      path: '/resources/tools'
      fullPath: '/resources/tools'
      preLoaderRoute: typeof ResourcesToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/documentation': {
      id: '/resources/documentation'
      path: '/resources/documentation'
      fullPath: '/resources/documentation'
      preLoaderRoute: typeof ResourcesDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$submissionId': {
      id: '/feedback/$submissionId'
      path: '/feedback/$submissionId'
      fullPath: '/feedback/$submissionId'
      preLoaderRoute: typeof FeedbackSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id/': {
      id: '/challenges/$id/'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SignupRoute: SignupRoute,
  FeedbackSubmissionIdRoute: FeedbackSubmissionIdRoute,
  ResourcesDocumentationRoute: ResourcesDocumentationRoute,
  ResourcesToolsRoute: ResourcesToolsRoute,
  ResourcesVideosRoute: ResourcesVideosRoute,
  RoadmapAdvancedRoute: RoadmapAdvancedRoute,
  RoadmapBeginnerRoute: RoadmapBeginnerRoute,
  RoadmapIntermediateRoute: RoadmapIntermediateRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ChallengesIdIndexRoute: ChallengesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
