/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as FeedbackSubmissionIdRouteImport } from './routes/feedback/$submissionId'
import { Route as RoadmapPathIdIndexRouteImport } from './routes/roadmap/$pathId/index'
import { Route as ChallengesIdIndexRouteImport } from './routes/challenges/$id/index'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSubmissionIdRoute = FeedbackSubmissionIdRouteImport.update({
  id: '/feedback/$submissionId',
  path: '/feedback/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapPathIdIndexRoute = RoadmapPathIdIndexRouteImport.update({
  id: '/roadmap/$pathId/',
  path: '/roadmap/$pathId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdIndexRoute = ChallengesIdIndexRouteImport.update({
  id: '/challenges/$id/',
  path: '/challenges/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/feedback/$submissionId': typeof FeedbackSubmissionIdRoute
  '/challenges': typeof ChallengesIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/challenges/$id': typeof ChallengesIdIndexRoute
  '/roadmap/$pathId': typeof RoadmapPathIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/feedback/$submissionId': typeof FeedbackSubmissionIdRoute
  '/challenges': typeof ChallengesIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/challenges/$id': typeof ChallengesIdIndexRoute
  '/roadmap/$pathId': typeof RoadmapPathIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/feedback/$submissionId': typeof FeedbackSubmissionIdRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/challenges/$id/': typeof ChallengesIdIndexRoute
  '/roadmap/$pathId/': typeof RoadmapPathIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/profile'
    | '/progress'
    | '/feedback/$submissionId'
    | '/challenges'
    | '/feedback'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/challenges/$id'
    | '/roadmap/$pathId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/profile'
    | '/progress'
    | '/feedback/$submissionId'
    | '/challenges'
    | '/feedback'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/challenges/$id'
    | '/roadmap/$pathId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/profile'
    | '/progress'
    | '/feedback/$submissionId'
    | '/challenges/'
    | '/feedback/'
    | '/resources/'
    | '/roadmap/'
    | '/settings/'
    | '/challenges/$id/'
    | '/roadmap/$pathId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  FeedbackSubmissionIdRoute: typeof FeedbackSubmissionIdRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ChallengesIdIndexRoute: typeof ChallengesIdIndexRoute
  RoadmapPathIdIndexRoute: typeof RoadmapPathIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$submissionId': {
      id: '/feedback/$submissionId'
      path: '/feedback/$submissionId'
      fullPath: '/feedback/$submissionId'
      preLoaderRoute: typeof FeedbackSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/$pathId/': {
      id: '/roadmap/$pathId/'
      path: '/roadmap/$pathId'
      fullPath: '/roadmap/$pathId'
      preLoaderRoute: typeof RoadmapPathIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id/': {
      id: '/challenges/$id/'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  FeedbackSubmissionIdRoute: FeedbackSubmissionIdRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ChallengesIdIndexRoute: ChallengesIdIndexRoute,
  RoadmapPathIdIndexRoute: RoadmapPathIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
